/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ccodeKata;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public String getGreeting(String name){
        return name == null ? getGreeting() : String.format("Hello %s!", name);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
