/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ccodeKata;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    private final App subject = new App();

    @Test
    void appHasAGreeting() {
        assertNotNull(subject.getGreeting(), "app should have a greeting");
    }

    @Test
    void greetingCanIncludeArgs() {
        String greeting = subject.getGreeting("Name");
        assertNotNull(greeting);
        assertEquals("Hello Name!", greeting);
    }
}
